name: 'Process Batch Action'
description: 'Processes a batch of tasks in parallel'
inputs:
  batch_tasks:
    description: 'Comma-separated list of tasks for this batch'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate task matrix
      id: generate-matrix
      run: |
        # Split batch tasks into array
        IFS=',' read -r -a tasks <<< "${{ inputs.batch_tasks }}"
        MATRIX_JSON=$(printf '%s\n' "${tasks[@]}" | jq -R . | jq -s '{ "task": . }' -c)
        echo "Generated task matrix: $MATRIX_JSON"
        
        # Output matrix for strategy
        echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
      shell: bash
    - name: Process Task
      strategy:
      matrix: ${{ fromJson(needs.process-batch.outputs.matrix) }}
      run: |
        echo "Processing task: ${{ matrix.task }}"
        ls -al
        sleep 1s
      shell: bash
      # Add more steps here as needed
