name: Dynamic Task Workflow

on:
  workflow_dispatch:
    inputs:
      task_names:
        description: 'Comma-separated list of task names (e.g., task1, task2, task3)'
        required: true
      batch_index:
        description: 'Optional batch index for splitting tasks (default: 0)'
        default: '0'
        required: false

jobs:
  split-and-dispatch:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
      should_dispatch: ${{ steps.generate-matrix.outputs.should_dispatch }}
      next_workflow_run_id: ${{ steps.dispatch-next-batch.outputs.workflow_run_id }}
    steps:
      - name: Generate task matrix and check for additional batches
        id: generate-matrix
        run: |
          IFS=',' read -r -a tasks <<< "${{ github.event.inputs.task_names }}"
          MAX_TASKS=256
          TOTAL_TASKS=${#tasks[@]}
          BATCH_INDEX=${{ github.event.inputs.batch_index }}
          START=$((BATCH_INDEX * MAX_TASKS))
          END=$((START + MAX_TASKS))

          if [ $END -gt $TOTAL_TASKS ]; then
            END=$TOTAL_TASKS
          fi

          # Extract tasks for this batch
          BATCH_TASKS=("${tasks[@]:$START:$MAX_TASKS}")

          # Generate JSON matrix with proper formatting
          MATRIX_JSON=$(printf '%s\n' "${BATCH_TASKS[@]}" | jq -R . | jq -s '{ "task": . }')
          echo "Generated matrix: $MATRIX_JSON"

          # Write to GITHUB_OUTPUT
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

          # Check if more batches are needed
          if [ $END -lt $TOTAL_TASKS ]; then
            echo "should_dispatch=true" >> $GITHUB_OUTPUT
          else
            echo "should_dispatch=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Dispatch next batch and get run ID
        id: dispatch-next-batch
        if: steps.generate-matrix.outputs.should_dispatch == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NEXT_BATCH=$(( ${{ github.event.inputs.batch_index }} + 1 ))
          RUN_ID=$(gh workflow run "${{ github.workflow }}" \
            -f task_names="${{ github.event.inputs.task_names }}" \
            -f batch_index="$NEXT_BATCH" \
            --ref "${{ github.ref }}" --json | jq -r '.id')
          echo "Dispatched workflow run ID: $RUN_ID"
          echo "workflow_run_id=$RUN_ID" >> $GITHUB_OUTPUT
        shell: bash

      - name: Wait for dispatched workflow to complete
        if: steps.generate-matrix.outputs.should_dispatch == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_ID=${{ steps.dispatch-next-batch.outputs.workflow_run_id }}
          echo "Waiting for workflow run $RUN_ID to complete..."
          while true; do
            STATUS=$(gh run view "$RUN_ID" --repo "${{ github.repository }}" --json conclusion,status | jq -r '.status')
            CONCLUSION=$(gh run view "$RUN_ID" --repo "${{ github.repository }}" --json conclusion,status | jq -r '.conclusion')
            echo "Current status: $STATUS, conclusion: $CONCLUSION"
            if [ "$STATUS" = "completed" ]; then
              if [ "$CONCLUSION" = "success" ]; then
                echo "Dispatched workflow completed successfully."
                exit 0
              else
                echo "Dispatched workflow failed with conclusion: $CONCLUSION"
                exit 1
              fi
            fi
            sleep 10s
          done
        shell: bash

  process-tasks:
    needs: split-and-dispatch
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.split-and-dispatch.outputs.matrix) }}
    steps:
      - name: Print task name
        run: |
          echo "Processing task: ${{ matrix.task }}"
          sleep 1s
        shell: bash
