name: Inner Task Workflow

on:
  workflow_call:
    inputs:
      batch_tasks:
        description: 'Comma-separated list of tasks for this batch'
        required: true
        type: string

jobs:
  process-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Moved here from outer workflow

      - name: Generate task matrix
        id: generate-matrix
        run: |
          # Split batch tasks into array
          IFS=',' read -r -a tasks <<< "${{ inputs.batch_tasks }}"
          MATRIX_JSON=$(printf '%s\n' "${tasks[@]}" | jq -R . | jq -s '{ "task": . }' -c)
          echo "Generated task matrix: $MATRIX_JSON"
          
          # Output matrix for strategy
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT
        shell: bash

    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}

  execute-tasks:
    needs: process-batch
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.process-batch.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Added here too, if tasks need repo files

      - name: Process Task
        run: |
          echo "Processing task: ${{ matrix.task }}"
          sleep 1s
        shell: bash
      # Add more steps here as needed
