name: Dynamic Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      tasks:
        description: 'Comma-separated list of tasks'
        required: true
        default: 'task1,task2,task3,task1,task2,task3'  # Optional: Set a default value

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.value }}  # Reference step output correctly
    steps:
      - name: Generate a List
        id: generate
        run: |
          # Use the input parameter 'tasks' as comma_separated_list
          comma_separated_list="${{ github.event.inputs.tasks }}"
          # Split into array, deduplicate, and convert back to JSON
          json_array=$(echo -n "$comma_separated_list" | jq -R -s 'split(",") | unique')
          # Properly escape and format the JSON for GitHub Actions output
          echo "value=$(echo "$json_array" | jq -c .)" >> $GITHUB_OUTPUT

  dynamic-matrix-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2  # Limit concurrent tasks to 2
      matrix:
        task: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}  # Correctly parse JSON
    steps:
      - name: Process Task
        run: |
          echo "Processing task: ${{ matrix.task }}"
          sleep 20
          echo "Processed task: ${{ matrix.task }}"
