name: Dynamic Matrix Workflow

on: [push]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}  # Reference step output correctly
    steps:
      - name: Generate a Comma-Separated List
        id: generate
        run: echo "task1,task2,task3" > matrix.txt  # Save comma-separated tasks to a file

      - name: Set Matrix Output
        id: set-matrix
        run: echo "::set-output name=matrix::$(cat matrix.txt)"  # Set output as comma-separated list

  dynamic-matrix-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ${{ fromJson('["' + needs.generate-matrix.outputs.matrix | replace(',', '","') + '"]') }}  # Convert comma-separated list to JSON array
    steps:
      - name: Process Task
        run: echo "Processing task: ${{ matrix.task }}"
