name: Dynamic Matrix Workflow

on: [push]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.value }}  # Reference step output correctly
    steps:
      - name: Generate a List
        id: generate
        run: |
          # echo '["task1", "task2", "task3"]' > matrix.json  # Save list to file
          # echo "value='["task1", "task2", "task3"]'" >> $GITHUB_OUTPUT
          echo "value=$(echo '["task1", "task2", "task3"]' | jq -c .)" >> $GITHUB_OUTPUT 

      - name: Set Matrix Output
        id: set-matrix
        run: echo "::set-output name=matrix::$(jq -c . matrix.json)"  # Set output properly

  dynamic-matrix-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}  # Correctly parse JSON
    steps:
      - name: Process Task
        run: |
          echo "Processing task: ${{ matrix.task }}"
