name: Dynamic Matrix Workflow

on: [push]

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.value }}  # Reference step output correctly
    steps:
      - name: Generate a Comma-Separated List
        id: generate
        run: echo "value=task1,task2,task3" >> $GITHUB_OUTPUT

  dynamic-matrix-job:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: ${{ needs.generate-matrix.outputs.matrix }}  # Use raw comma-separated list directly
    steps:
      - name: Process Task
        run: echo Processing task ${{ matrix.task }}
