
name: Trigger Repo B Workflow

on:
#  push:
#    branches: ['main']
   pull_request:          
     branches: ['main']
     types: [closed]

jobs:
  trigger:
    if: github.event.pull_request.merged == true
    name: Bump Version and Tag
    runs-on: ubuntu-latest
#    permissions:
#      # Grant write access to send repository_dispatch
#      actions: write
#      contents: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Github Tag Bump
          id: tag-bump
          uses: anothrNick/github-tag-action@1.67.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
#            DEFAULT_BUMP: patch
        - name: run command
          run: |
            echo $GITHUB_REF_NAME - $GITHUB_REF
#        - name: Trigger Repo B
#          uses: peter-evans/repository-dispatch@v2
#          with:
#            token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default token
#            repository: my-org-mk/test-repo-b     # Replace with your org/repo-b
#            event-type: run_workflow           # Must match Repo B's event type
  deploy:
    needs: [trigger]
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: deploy command
        run: |
            echo deploy command
