name: Trigger Repo B Workflow

on:
 pull_request:
  types: [opened, reopened, synchronize]
#on:
# push:
#  branches: [main]
   
    
jobs:
#  trigger:
#    name: Bump Version and {{github. base_ref }} - {{github.ref}} - {{github.ref_name}}
#    runs-on: ubuntu-latest
#    environment: dev1
#    permissions:
#      # Grant write access to send repository_dispatch
#      actions: write
#      contents: write

#    steps:
#        - name: Checkout
#          uses: actions/checkout@v4
#        - name: Github Tag Bump
#          id: tag-bump
#          uses: anothrNick/github-tag-action@1.67.0
#          env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
  trigger-remote-workflow:
#    needs: [trigger]
    runs-on:
      labels: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Print brnach name
      run: |
       echo Current branch is: ${{ github.ref_name }}
    - name: Get credentials
      id: get-pat
      run: |
        json=$(echo "{ \"user\": \"ENVGIT_moto\", \"token\": \"${{ secrets.MY_SECRET_KEY }}\" }" | jq '.')
        pat=$(echo "$json" | jq -r '.token')        
        echo "PAT length: ${#pat} characters"
        echo "value=$pat" >> "$GITHUB_OUTPUT"
        echo "::add-mask::$pat"

    - name: Check PAT
      run: |
        pat="${{ steps.get-pat.outputs.value }}"
        echo "PAT length: ${#pat} characters"  # Count and print the length

    - name: Trigger Repo B - 1
      run: |
        curl -f -X POST \
             -H "Authorization: Bearer ${{ steps.get-pat.outputs.value }}" \
             -H "Accept: application/vnd.github+json" \
             -d '{"event_type": "run_workflow"}' \
             https://api.github.com/repos/my-org-mk/test-repo-b/dispatches
            
#            DEFAULT_BUMP: patch
#        - name: run command
#          run: |
#            echo $GITHUB_REF_NAME - $GITHUB_REF
    - name: Trigger Repo B - 2
      uses: peter-evans/repository-dispatch@v3
      with:
       token: ${{ steps.get-pat.outputs.value }}  # Uses the default token
       repository: my-org-mk/test-repo-b    # Replace with your org/repo-b
       event-type: run_workflow           # Must match Repo B's event type
       
#  comment-on-pr:
#    needs: [trigger]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Add comment to PR
#        run: |
#          gh api repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
#            -f body="🚀 Thank you for your pull request! We will review it soon."
#        env:
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Github Tag Bump
      id: tag-bump
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
    
    - name: Github Tag Bump Major
      id: tag-bump-major
      if: steps.tag-bump.outputs.new_tag != ''
      run: |        
        major_tag=$(echo ${{ steps.tag-bump.outputs.new_tag }} | cut -d'.' -f1)
        git tag -f $major_tag
        git push origin $major_tag --force
        echo "value=$major_tag" >> $GITHUB_OUTPUT

    - name: Put ecr tags      
      id: build-image
      env:
        NEW_TAG: ${{ steps.tag-bump.outputs.new_tag }}
        MAJOR_TAG: ${{ steps.tag-bump-major.outputs.value }}
      run: |
        if [ -n "${{ env.NEW_TAG }}" ]; then
          echo acr put ${{ env.NEW_TAG }}
        fi
        if [ -n "${{ env.MAJOR_TAG }}" ]; then
          echo acr put ${{ env.MAJOR_TAG }}
        fi

