name: Trigger Repo B Workflow

on:
  push:
    branches: [main]

jobs:
  trigger:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Required to trigger external workflows
    steps:
      - name: Trigger RepoB via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -sSL \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/my-org-mk/test-repo-b/dispatches" \
            -d '{"event_type":"run_workflow"}'
