name: Trigger Repo B Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
#    permissions:
#      # Grant write access to send repository_dispatch
#      actions: write
#      contents: read
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Github Tag Bump
          id: tag-bump
          uses: anothrNick/github-tag-action@1.71.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: false
            INITIAL_VERSION: 1.-1.0
            DEFAULT_BUMP: minor
#      - name: Trigger Repo B
#        uses: peter-evans/repository-dispatch@v2
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the default token
#          repository: my-test-org/repo-b     # Replace with your org/repo-b
#          event-type: run_workflow           # Must match Repo B's event type
